import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/Header";
import { ReactNode } from "react";
import { getCurrentSession } from "@/actions/cookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  const session = await getCurrentSession();

  const user = session ? session.user : null;

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased min-h-[125vh]`}>
        <Header user={user} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
